In [3]:
import pandas as pd
import numpy as np

### Question 1
#### What's the version of Pandas that you installed?

In [3]:
pd.__version__

'1.5.3'

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 14:51:19--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: 'housing.csv'

     0K .......... .......... .......... .......... ..........  3%  301K 4s
    50K .......... .......... .......... .......... ..........  7%  433K 4s
   100K .......... .......... .......... .......... .......... 10% 1.17M 3s
   150K .......... .......... .......... .......... .......... 14% 1.65M 2s
   200K .......... .......... .......... .......... .......... 17%  623K 2s
   250K .......... .......... .......... .......... .......... 21% 1.17M 2s
   300K .......... .......... .......... .......... .......... 25% 1.99M 1s
   350K ........

In [28]:
df=pd.read_csv('housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

### Question 2
#### How many columns are in the dataset?

In [11]:
num_cols=df.shape[1]
print('Number of columns:',num_cols)

Number of columns: 10


### Question 3
#### Which columns in the dataset have missing values?

In [17]:
missing_values = df.isnull().sum()
missing_values
columns_with_missing_values = missing_values[missing_values > 0]
print('columns with missing values:', columns_with_missing_values)

columns with missing values: total_bedrooms    207
dtype: int64


### Question 4
#### How many unique values does the ocean_proximity column have?

In [21]:
unique_values_count = df['ocean_proximity'].nunique()
print('Number of unique values in ocean_proximity column is:',unique_values_count)

Number of unique values in ocean_proximity column is: 5


### Question 5
#### What's the average value of the median_house_value for the houses located near the bay?

In [32]:
near_bay_df = df[df['ocean_proximity']=='NEAR BAY']
average_value_of_median_house_near_bay = near_bay_df['median_house_value'].mean()
print('Average value of median_house_value for houses located near the bay is :',average_value_of_median_house_near_bay)

Average value of median_house_value for houses located near the bay is : 259212.31179039303


### Question 6
#### Calculate the average of total_bedrooms column in the dataset.
#### Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
#### Now, calculate the average of total_bedrooms again.
#### Has it changed?


In [47]:
average_of_total_bedrooms_before_fillna = df['total_bedrooms'].mean()

print('Average of total bedrooms before fillna:',average_of_total_bedrooms_before_fillna)

df['total_bedrooms'].fillna(average_of_total_bedrooms_before_fillna,inplace = True)

average_of_total_bedrooms_after_fillna = df['total_bedrooms'].mean()

print('Average of total bedrooms after fillna :',average_of_total_bedrooms_after_fillna)


# Create a copy of the DataFrame
df_unfilled = df.copy()

# Restore missing values (replace the filled values with NaN)
df_unfilled['total_bedrooms'].replace(df['total_bedrooms'].mean(), np.nan, inplace=True)

Average of total bedrooms before fillna: 537.8705525375617
Average of total bedrooms after fillna : 537.8705525375617


### Question 7
#### Select all the options located on islands.
#### Select only columns housing_median_age, total_rooms, total_bedrooms.
#### Get the underlying NumPy array. Let's call it X.
#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#### Compute the inverse of XTX.
#### Create an array y with values [950, 1300, 800, 1000, 1300].
#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#### What's the value of the last element of w?

In [52]:
#Select options located on Islands
Islands_df = df[df['ocean_proximity']=='INLAND']
Islands_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
954      -121.92     37.64                46.0       1280.0           209.0   
957      -121.90     37.66                18.0       7397.0          1137.0   
965      -121.88     37.68                23.0       2234.0           270.0   
967      -121.88     37.67                16.0       4070.0           624.0   
968      -121.88     37.67                25.0       2244.0           301.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
954         512.0       208.0         5.1406            315600.0   
957        3126.0      1115.0         6.4994            323000.0   
965         854.0       286.0         7.3330            337200.0   
967        1543.0       577.0         6.5214            311500.0   
968         937.0       324.0         6.4524            296900.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
954            INLAND  
957            INLAND  
965            INLAND  
967            INLAND  
968            INLAND  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[6551 rows x 10 columns]

In [53]:
#Select only columns housing_median_age, total_rooms, total_bedrooms.
Selected_columns =['housing_median_age','total_rooms','total_bedrooms']
Selected_data = Islands_df[Selected_columns]
Selected_data

housing_median_age  total_rooms  total_bedrooms
954                  46.0       1280.0           209.0
957                  18.0       7397.0          1137.0
965                  23.0       2234.0           270.0
967                  16.0       4070.0           624.0
968                  25.0       2244.0           301.0
...                   ...          ...             ...
20635                25.0       1665.0           374.0
20636                18.0        697.0           150.0
20637                17.0       2254.0           485.0
20638                18.0       1860.0           409.0
20639                16.0       2785.0           616.0

[6551 rows x 3 columns]

In [56]:
#Get the underlying NumPy array. Let's call it X.
X = Selected_data.values
X

array([[  46., 1280.,  209.],
       [  18., 7397., 1137.],
       [  23., 2234.,  270.],
       ...,
       [  17., 2254.,  485.],
       [  18., 1860.,  409.],
       [  16., 2785.,  616.]])

In [58]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX=np.dot(X.T,X)
XTX

array([[4.80538300e+06, 3.63375522e+08, 7.32417454e+07],
       [3.63375522e+08, 8.56703556e+10, 1.61906920e+10],
       [7.32417454e+07, 1.61906920e+10, 3.16010580e+09]])

In [59]:
#Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 3.27228666e-07,  1.42983863e-09, -1.49099045e-08],
       [ 1.42983863e-09,  3.74177664e-10, -1.95022559e-09],
       [-1.49099045e-08, -1.95022559e-09,  1.06539248e-08]])

In [60]:
#Create an array y with values [950, 1300, 800, 1000, 1300].
y = np.array([950,1300,800,1000,1300])

In [83]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [85]:
# Retrieve the value of the last element of w
last_w_value = w[-1]
print('Value of the last element of w:', last_w_value)

Value of the last element of w: 5.6992294550655656
